box:
  image: dbourasseau/mediahomedelta
  ports:
   - "9998:9998"
  volumes:
   - /home/ehg/mediahome/data:/var/www/html
   - /tmp:/tmp
   - /home/ehg/mediahome/config:/etc/mediahome
  links:
   - db
   - worker
   - squid
db:
  image: mysql:5.6
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=mediahome
   - MYSQL_USER=mediahome
   - MYSQL_PASSWORD=mediahome
worker:
  image: dngroup/media-home-worker
  volumes:
   - /home/ehg/mediahome/data:/var/www/html
   - /tmp:/tmp
squid:
  image: dbourasseau/squid
  ports:
    - "8055:80"
    - "3128:3128"
  volumes:
    - /srv/docker/squid/cache:/var/spool/squid3
